### ISSUE TITLE
API incorrectly decoding paginated response due to Unmarshal error with time.Time

### ISSUE THREAD

**Issue by LanderTome** [textmagic/textmagic-rest-go-v2#1]
When using GetAllTemplates to retrieve list of all templates. The paginated response only includes the first item. The rest of the templates are not returned.

It appears that the Unmarshaling of the response generates an error while decoding the LastModified time.Time.

The format used to decode the time is `"2006-01-02T15:04:05Z07:00"`
However, the json response is (example) `"2019-12-03T00:26:24+0000"`

Go cannot decode the "+0000" with "Z07:00"

This error happens silently because Go simply stops Unmarshaling and returns an error. 
But then, if the response code is 200 (which it is because the REST call was successful), the function ultimately just returns the localVarReturnValue as is (even though it is missing information because of the Unmarshaling error).

This error probably affects more API calls that return paginated lists. I have not tested them.

Code to reproduce:
```
resp, _, _ := tm.GetAllTemplates(textmagic.TmAuth, &TextMagic.GetAllTemplatesOpts{
		Page:  optional.NewInt32(1),
		Limit: optional.NewInt32(50)
	})

println(len(resp.Resources))
```

The length will be `1` no matter how many templates there are because only the first item is returned.

**Comment by evgeniyparanyuk-textmagic** [comment]
Fixed in the latest version.
